
version: '3.7'

services:
  
  voedger:
    image: voedger/voedger:0.0.1-alpha
    volumes:
      - /etc/hosts:/etc/hosts
    environment:
      - VOEDGER_HTTP_PORT=8888
    ports:
      - "0.0.0.0:8888:8888"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.AppNode == true

    restart: unless-stopped
