
version: '3.7'

services:
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: voedger-cadvisor
    ports:
      - "0.0.0.0:8080:8080"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type == se

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
