# Copyright (c) 2023 Sigma-Soft, Ltd.
# @author Aleksei Ponomarev

version: '3.5'

services:

  scylla1:
    image: scylladb/scylla:4.5.3
    command: --seeds {{.DBNode1}},{{.DBNode2}},{{.DBNode3}} --listen-address 0.0.0.0  --broadcast-address {{.DBNode1}}  --broadcast-rpc-address {{.DBNode1}}
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
      - target: 9180
        published: 9180
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.DBNode1 == true
      replicas: 1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | awk '/^UN/ {print $$2}' | grep -w $$(getent hosts {{.DBNode1}} | awk '{print $$1}')"]
      interval: 15s
      timeout: 5s
      retries: 30  
    networks:
      - default
    volumes:
      - scylla1-data:/var/lib/scylla
      - ~/scylla/scylla.yaml:/etc/scylla/scylla.yaml
      - /etc/hosts:/etc/hosts

  scylla2:
    image: scylladb/scylla:4.5.3
    command: --seeds {{.DBNode1}},{{.DBNode2}},{{.DBNode3}} --listen-address 0.0.0.0  --broadcast-address {{.DBNode2}}  --broadcast-rpc-address {{.DBNode2}}
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
      - target: 9180
        published: 9180
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.DBNode2 == true
      replicas: 1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | awk '/^UN/ {print $$2}' | grep -w $$(getent hosts {{.DBNode2}} | awk '{print $$1}')"]
      interval: 15s
      timeout: 5s
      retries: 30  
    networks:
      - default
    volumes:
      - scylla2-data:/var/lib/scylla
      - ~/scylla/scylla.yaml:/etc/scylla/scylla.yaml
      - /etc/hosts:/etc/hosts

  scylla3:
    image: scylladb/scylla:4.5.3
    command: --seeds {{.DBNode1}},{{.DBNode2}},{{.DBNode3}} --listen-address 0.0.0.0  --broadcast-address {{.DBNode3}}  --broadcast-rpc-address {{.DBNode3}}
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
      - target: 9180
        published: 9180
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.DBNode3 == true
      replicas: 1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | awk '/^UN/ {print $$2}' | grep -w $$(getent hosts {{.DBNode3}} | awk '{print $$1}')"]
      interval: 15s
      timeout: 5s
      retries: 30  
    networks:
      - default
    volumes:
      - scylla3-data:/var/lib/scylla
      - ~/scylla/scylla.yaml:/etc/scylla/scylla.yaml
      - /etc/hosts:/etc/hosts

volumes:
  scylla1-data:
    driver: local
    driver_opts:
      type: node
      o: bind
      device: /var/lib/scylla
  scylla2-data:
    driver: local
    driver_opts:
      type: node
      o: bind
      device: /var/lib/scylla
  scylla3-data:
    driver: local
    driver_opts:
      type: node
      o: bind
      device: /var/lib/scylla

networks:
  default:
    driver: overlay
    attachable: true

