# Copyright (c) 2023 Sigma-Soft, Ltd.
# @author Aleksei Ponomarev

version: '3.5'

services:

  scylla1:
    image: scylladb/scylla:4.5.3
    command: --seeds {scylla1},{scylla2},{scylla3} --listen-address 0.0.0.0  --broadcast-address {scylla1}  --broadcast-rpc-address {scylla1}
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
      - target: 9180
        published: 9180
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.type == scylla1
      replicas: 1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | awk '/^UN/ {print $$2}' | grep -w '{scylla1}'"]
      interval: 15s
      timeout: 5s
      retries: 30  
    networks:
      - default
    volumes:
      - scylla1-data:/var/lib/scylla
      - ~/scylla/scylla.yaml:/etc/scylla/scylla.yaml

  scylla2:
    image: scylladb/scylla:4.5.3
    command: --seeds {scylla1},{scylla2},{scylla3} --listen-address 0.0.0.0  --broadcast-address {scylla2}  --broadcast-rpc-address {scylla2}
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
      - target: 9180
        published: 9180
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.type == scylla2
      replicas: 1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | awk '/^UN/ {print $$2}' | grep -w '{scylla2}'"]
      interval: 15s
      timeout: 5s
      retries: 30  
    networks:
      - default
    volumes:
      - scylla2-data:/var/lib/scylla
      - ~/scylla/scylla.yaml:/etc/scylla/scylla.yaml

  scylla3:
    image: scylladb/scylla:4.5.3
    command: --seeds {scylla1},{scylla2},{scylla3} --listen-address 0.0.0.0  --broadcast-address {scylla3}  --broadcast-rpc-address {scylla3}
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
      - target: 9180
        published: 9180
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.type == scylla3
      replicas: 1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | awk '/^UN/ {print $$2}' | grep -w '{scylla3}'"]
      interval: 15s
      timeout: 5s
      retries: 30  
    networks:
      - default
    volumes:
      - scylla3-data:/var/lib/scylla
      - ~/scylla/scylla.yaml:/etc/scylla/scylla.yaml

volumes:
  scylla1-data:
    driver: local
    driver_opts:
      type: node
      o: bind
      device: /var/lib/scylla
  scylla2-data:
    driver: local
    driver_opts:
      type: node
      o: bind
      device: /var/lib/scylla
  scylla3-data:
    driver: local
    driver_opts:
      type: node
      o: bind
      device: /var/lib/scylla

networks:
  default:
    driver: overlay
    attachable: true

