# Copyright (c) 2024 Sigma-Soft, Ltd.
# @author Aleksei Ponomarev

version: '3.8'

services:
  
  voedger:
    image: voedger/voedger:0.0.1-alpha
    extra_hosts:
      - "db-node-1:${VOEDGER_CE_NODE}"
    environment:
      - VOEDGER_HTTP_PORT=443
      - VOEDGER_ACME_DOMAINS=${VOEDGER_ACME_DOMAINS}
    restart: unless-stopped
