# Copyright (c) 2023 Sigma-Soft, Ltd.
# @author Aleksei Ponomarev

version: '3.5'

services:

  scylla1:
    image: scylladb/scylla:latest
#    network_mode: host  - docker compose options. Ignore in swarm cluster.
    command: --seeds 10.0.0.12,10.0.0.13 --listen-address 0.0.0.0  --broadcast-address 10.0.0.12  --broadcast-rpc-address 10.0.0.12
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
      - target: 9180
        published: 9180
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.type == scylla1
      replicas: 1
    networks:
      - default
    volumes:
      - scylla1-data:/var/lib/scylla

  scylla2:
    image: scylladb/scylla:latest
    network_mode: host 
    command: --seeds 10.0.0.12,10.0.0.13 --listen-address 0.0.0.0  --broadcast-address 10.0.0.13  --broadcast-rpc-address 10.0.0.13
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
      - target: 9180
        published: 9180
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.type == scylla2
      replicas: 1
    networks:
      - default
    volumes:
      - scylla2-data:/var/lib/scylla

  scylla3:
    image: scylladb/scylla:latest
    network_mode: host
    command: --seeds 10.0.0.12,10.0.0.13 --listen-address 0.0.0.0  --broadcast-address 10.0.0.14  --broadcast-rpc-address 10.0.0.14
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
      - target: 9180
        published: 9180
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.type == scylla3
      replicas: 1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN | wc -l | grep '^3$$'"]
      interval: 15s
      timeout: 5s
      retries: 30 
    networks:
      - default
    volumes:
      - scylla3-data:/var/lib/scylla

volumes:
  scylla1-data:
    driver: local
    driver_opts:
      type: node
      o: bind
      device: /var/lib/scylla
  scylla2-data:
    driver: local
    driver_opts:
      type: node
      o: bind
      device: /var/lib/scylla
  scylla3-data:
    driver: local
    driver_opts:
      type: node
      o: bind
      device: /var/lib/scylla

networks:
  default:
    driver: overlay
    attachable: true

