name: CI cmd

on:
  push:
    paths:
      - 'cmd/**'

jobs:
  call-workflow-ci-cmd:
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with: 
      test_folder: 'cmd'
      ignore_copyright: 'pkg/apps/sys.monitor/site.main'
      ignore_bp3: 'true'
      short_test: 'true'
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  call-workflow-cd_voeger:
    needs: call-workflow-ci-cd
    uses: ivvist/voedger/.github/workflows/cd-voedger.yml@main
    secrets:
      dockerusername: ${{ secrets.DOCKER_USERNAME }}
      dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
      personaltoken: ${{ secrets.PERSONAL_TOKEN }}
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}

