name: CI cmd

on:
  push:
    branches:
      - main
    paths:
      - "cmd/**"

jobs:
  call-workflow-ci-cmd-ctool:
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with:
      test_folder: "cmd/ctool/"
      ignore_copyright: "cmd/voedger/sys.monitor/site.main"
      short_test: "true"
      ignore_build: "true"
      go_race: "false"
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ""
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  call-workflow-ci-cmd-edger:
    needs: call-workflow-ci-cmd-ctool
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with:
      test_folder: "cmd/edger/"
      ignore_copyright: "cmd/voedger/sys.monitor/site.main"
      short_test: "true"
      ignore_build: "true"
      go_race: "false"
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ""
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  call-workflow-ci-cmd-vpm:
    needs: call-workflow-ci-cmd-edger
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with:
      test_folder: "cmd/vpm/"
      ignore_copyright: "cmd/voedger/sys.monitor/site.main"
      short_test: "true"
      ignore_build: "true"
      go_race: "false"
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ""
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  call-workflow-ci-cmd-voedger:
    needs: call-workflow-ci-cmd-vpm
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with:
      test_folder: "cmd/voedger/"
      ignore_copyright: "cmd/voedger/sys.monitor/site.main"
      short_test: "true"
      ignore_build: "true"
      go_race: "false"
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ""
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  call-workflow-cd-voeger:
    needs: call-workflow-ci-cmd-voedger
    if: github.repository == 'voedger/voedger'
    uses: voedger/voedger/.github/workflows/cd-voedger.yml@main
    secrets:
      dockerusername: ${{ secrets.DOCKER_USERNAME }}
      dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
      personaltoken: ${{ secrets.PERSONAL_TOKEN }}
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
