name: CI design

on:
  pull_request_target:
    paths:
      - 'design/**'

jobs:
  auto-merge-pr:
    uses: voedger/voedger/.github/workflows/merge.yml@main
    secrets:
      personaltoken: ${{ secrets.REPOREADING_TOKEN }}

