name: Daily test suite

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  call-workflow-ci:
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with: 
      ignore_copyright: 'pkg/apps/sys.monitor/site.main'
      ignore_bp3: 'true'
      short_test: 'false'
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  call-workflow-vulncheck:
    needs: call-workflow-ci
    uses: voedger/voedger/.github/workflows/ci-vulncheck.yml@main
    secrets:
      personaltoken: ${{ secrets.REPOREADING_TOKEN }}
  call-workflow-cd-voeger:
    needs: call-workflow-vulncheck
    uses: voedger/voedger/.github/workflows/cd-voedger.yml@main
    secrets:
      dockerusername: ${{ secrets.DOCKER_USERNAME }}
      dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
      personaltoken: ${{ secrets.PERSONAL_TOKEN }}
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}

