name: CI pkg-cmd

on:
  push:
    paths:
      - 'pkg/**'


jobs:
  call-workflow-ci-pkg:
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with: 
      test_folder: 'pkg'
      ignore_copyright: 'pkg/apps/sys.monitor/site.main'
      ignore_bp3: 'true'
      short_test: 'true'
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  build:
    needs: call-workflow-ci-pkg
    name: build
    runs-on: ubuntu-latest
    
    outputs:
      ibp3: ${{ steps.setignore.outputs.ignore_bp3 }}

    steps:
    - name: Set Ignore Build BP3
      id: setignore
      run: |
        if [[ ${{ github.repository }} == 'voedger/voedger' ]]; then
          echo "ignore_bp3=false" >> "$GITHUB_OUTPUT"
        else
          echo "ignore_bp3=true" >> "$GITHUB_OUTPUT"
        fi

  call-workflow-ci-cmd:
    needs: build
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with: 
      test_folder: 'cmd'
      ignore_copyright: 'pkg/apps/sys.monitor/site.main'
      short_test: 'true'
      ignore_bp3: ${{ needs.build.outputs.ibp3 }}
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  call-workflow-cd_voeger:
    needs: call-workflow-ci-cmd
    if: github.repository == 'voedger/voedger'
    uses: voedger/voedger/.github/workflows/cd-voedger.yml@main
    secrets:
      dockerusername: ${{ secrets.DOCKER_USERNAME }}
      dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
      personaltoken: ${{ secrets.PERSONAL_TOKEN }}
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}


