name: CI pkg-cmd

on:
  push:
    paths:
      - 'pkg/**'
  pull_request:
    paths:
      - 'pkg/**'
  pull_request_target:
    paths:
      - 'pkg/**'

jobs:
  call-workflow-ci-pkg:
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with: 
      test_folder: 'pkg'
      ignore_copyright: 'pkg/apps/sys.monitor/site.main'
      ignore_bp3: 'true'
      short_test: 'true'
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  call-workflow-ci-cmd:
    needs: call-workflow-ci-pkg
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with: 
      test_folder: 'cmd'
      ignore_copyright: 'pkg/apps/sys.monitor/site.main'
      short_test: 'true'
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  auto-merge-pr:
    needs: call-workflow-ci-cmd
    if: github.event_name == 'pull_request_target'
    uses: voedger/voedger/.github/workflows/merge.yml@main
    secrets:
      personaltoken: ${{ secrets.REPOREADING_TOKEN }}

