name: Vulnerability management

on: workflow_call

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Check vulnerability 
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck voedger/voedger/...



