name: Vulnerability management

on: workflow_call

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21.3'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Vulnerability management
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/execgovuln.sh | bash 

