name: Merge PR

on:
  workflow_call:
    secrets:
      personaltoken:
        required: true

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Merge PR
      env: 
        GH_TOKEN: ${{ github.token }}
        token: ${{ secrets.personaltoken }}
        repo: ${{ GITHUB.REPOSITORY }}
        pr_number: ${{ github.event.number }}
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/domergepr.sh | bash 
