name: CI golang

on: [push, pull_request]

jobs:
  call-workflow-ci:
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with: 
      ignore_copyright: 'apps/sys.monitor/site.main'
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}